// Copyright 2013 Michael Yang. All rights reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.
package id3

var (
	V3FrameTypeMap = map[string]FrameType{
		"AENC": FrameType{id: "AENC", description: "Audio encryption"},
		"APIC": FrameType{id: "APIC", description: "Attached picture"},
		"COMM": FrameType{id: "COMM", description: "Comments"},
		"COMR": FrameType{id: "COMR", description: "Commercial frame"},
		"ENCR": FrameType{id: "ENCR", description: "Encryption method registration"},
		"EQUA": FrameType{id: "EQUA", description: "Equalization"},
		"ETCO": FrameType{id: "ETCO", description: "Event timing codes"},
		"GEOB": FrameType{id: "GEOB", description: "General encapsulated object"},
		"GRID": FrameType{id: "GRID", description: "Group identification registration"},
		"IPLS": FrameType{id: "IPLS", description: "Involved people list"},
		"LINK": FrameType{id: "LINK", description: "Linked information"},
		"MCDI": FrameType{id: "MCDI", description: "Music CD identifier"},
		"MLLT": FrameType{id: "MLLT", description: "MPEG location lookup table"},
		"OWNE": FrameType{id: "OWNE", description: "Ownership frame"},
		"PRIV": FrameType{id: "PRIV", description: "Private frame"},
		"PCNT": FrameType{id: "PCNT", description: "Play counter"},
		"POPM": FrameType{id: "POPM", description: "Popularimeter"},
		"POSS": FrameType{id: "POSS", description: "Position synchronisation frame"},
		"RBUF": FrameType{id: "RBUF", description: "Recommended buffer size"},
		"RVAD": FrameType{id: "RVAD", description: "Relative volume adjustment"},
		"RVRB": FrameType{id: "RVRB", description: "Reverb"},
		"SYLT": FrameType{id: "SYLT", description: "Synchronized lyric/text"},
		"SYTC": FrameType{id: "SYTC", description: "Synchronized tempo codes"},
		"TALB": FrameType{id: "TALB", description: "Album/Movie/Show title"},
		"TBPM": FrameType{id: "TBPM", description: "BPM (beats per minute)"},
		"TCOM": FrameType{id: "TCOM", description: "Composer"},
		"TCON": FrameType{id: "TCON", description: "Content type"},
		"TCOP": FrameType{id: "TCOP", description: "Copyright message"},
		"TDAT": FrameType{id: "TDAT", description: "Date"},
		"TDLY": FrameType{id: "TDLY", description: "Playlist delay"},
		"TENC": FrameType{id: "TENC", description: "Encoded by"},
		"TEXT": FrameType{id: "TEXT", description: "Lyricist/Text writer"},
		"TFLT": FrameType{id: "TFLT", description: "File type"},
		"TIME": FrameType{id: "TIME", description: "Time"},
		"TIT1": FrameType{id: "TIT1", description: "Content group description"},
		"TIT2": FrameType{id: "TIT2", description: "Title/songname/content description"},
		"TIT3": FrameType{id: "TIT3", description: "Subtitle/Description refinement"},
		"TKEY": FrameType{id: "TKEY", description: "Initial key"},
		"TLAN": FrameType{id: "TLAN", description: "Language(s)"},
		"TLEN": FrameType{id: "TLEN", description: "Length"},
		"TMED": FrameType{id: "TMED", description: "Media type"},
		"TOAL": FrameType{id: "TOAL", description: "Original album/movie/show title"},
		"TOFN": FrameType{id: "TOFN", description: "Original filename"},
		"TOLY": FrameType{id: "TOLY", description: "Original lyricist(s)/text writer(s)"},
		"TOPE": FrameType{id: "TOPE", description: "Original artist(s)/performer(s)"},
		"TORY": FrameType{id: "TORY", description: "Original release year"},
		"TOWN": FrameType{id: "TOWN", description: "File owner/licensee"},
		"TPE1": FrameType{id: "TPE1", description: "Lead performer(s)/Soloist(s)"},
		"TPE2": FrameType{id: "TPE2", description: "Band/orchestra/accompaniment"},
		"TPE3": FrameType{id: "TPE3", description: "Conductor/performer refinement"},
		"TPE4": FrameType{id: "TPE4", description: "Interpreted, remixed, or otherwise modified by"},
		"TPOS": FrameType{id: "TPOS", description: "Part of a set"},
		"TPUB": FrameType{id: "TPUB", description: "Publisher"},
		"TRCK": FrameType{id: "TRCK", description: "Track number/Position in set"},
		"TRDA": FrameType{id: "TRDA", description: "Recording dates"},
		"TRSN": FrameType{id: "TRSN", description: "Internet radio station name"},
		"TRSO": FrameType{id: "TRSO", description: "Internet radio station owner"},
		"TSIZ": FrameType{id: "TSIZ", description: "Size"},
		"TSRC": FrameType{id: "TSRC", description: "ISRC (international standard recording code)"},
		"TSSE": FrameType{id: "TSSE", description: "Software/Hardware and settings used for encoding"},
		"TYER": FrameType{id: "TYER", description: "Year"},
		"TXXX": FrameType{id: "TXXX", description: "User defined text information frame"},
		"UFID": FrameType{id: "UFID", description: "Unique file identifier"},
		"USER": FrameType{id: "USER", description: "Terms of use"},
		"USLT": FrameType{id: "USLT", description: "Unsychronized lyric/text transcription"},
		"WCOM": FrameType{id: "WCOM", description: "Commercial information"},
		"WCOP": FrameType{id: "WCOP", description: "Copyright/Legal information"},
		"WOAF": FrameType{id: "WOAF", description: "Official audio file webpage"},
		"WOAR": FrameType{id: "WOAR", description: "Official artist/performer webpage"},
		"WOAS": FrameType{id: "WOAS", description: "Official audio source webpage"},
		"WORS": FrameType{id: "WORS", description: "Official internet radio station homepage"},
		"WPAY": FrameType{id: "WPAY", description: "Payment"},
		"WPUB": FrameType{id: "WPUB", description: "Publishers official webpage"},
		"WXXX": FrameType{id: "WXXX", description: "User defined URL link frame"},
	}
)
